const words = [
  { word: 'Apple', meaning: 'A fruit' },
  { word: 'Ball', meaning: 'A round object' },
  { word: 'Cat', meaning: 'A small domesticated carnivorous mammal' },
  { word: 'Dog', meaning: 'A domesticated carnivorous mammal' },
  { word: 'Elephant', meaning: 'A large herbivorous mammal' },
  { word: 'Flower', meaning: 'The reproductive structure in flowering plants' },
  { word: 'Giraffe', meaning: 'A tall, long-necked, spotted ruminant' },
  { word: 'House', meaning: 'A building for human habitation' },
  { word: 'Ice', meaning: 'Frozen water' },
  { word: 'Jacket', meaning: 'A piece of clothing worn on the upper body' },
  { word: 'Kite', meaning: 'A toy that flies in the air' },
  { word: 'Lion', meaning: 'A large carnivorous feline mammal' },
  { word: 'Mountain', meaning: 'A large natural elevation of the earth' },
  { word: 'Nest', meaning: 'A structure built by birds for laying eggs' },
  { word: 'Orange', meaning: 'A round citrus fruit' },
  { word: 'Pencil', meaning: 'An instrument for writing or drawing' },
  { word: 'Queen', meaning: 'The female ruler of an independent state' },
  { word: 'River', meaning: 'A large natural stream of water' },
  { word: 'Sun', meaning: 'The star at the center of our solar system' },
  { word: 'Tree', meaning: 'A woody perennial plant' },
  { word: 'Umbrella', meaning: 'A device for protection against rain or sun' },
  { word: 'Violin', meaning: 'A stringed musical instrument' },
  { word: 'Water', meaning: 'A transparent, tasteless liquid essential for life' },
  { word: 'Xylophone', meaning: 'A musical instrument with wooden bars' },
  { word: 'Yacht', meaning: 'A medium-sized sailboat' },
  { word: 'Zebra', meaning: 'An African wild horse with black-and-white stripes' }
];

export default words;
