apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-schema-and-data-job
  namespace: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql-schema-and-data
        image: google/cloud-sdk:slim  # This image includes gsutil
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Downloading SQL and CSV files from GCS...";
            gsutil cp gs://alexbu-gke-dev-d-lexitrail-mysql-files/schema.sql /mnt/sql/schema.sql;
            gsutil cp gs://alexbu-gke-dev-d-lexitrail-mysql-files/csv/wordsets.csv /mnt/csv/wordsets.csv;
            gsutil cp gs://alexbu-gke-dev-d-lexitrail-mysql-files/csv/words.csv /mnt/csv/words.csv;
            echo "Running MySQL script...";
            mysql -h mysql -u root -p????????? < /mnt/sql/schema.sql;
        volumeMounts:
        - name: sql-volume
          mountPath: /mnt/sql
        - name: csv-volume
          mountPath: /mnt/csv
      restartPolicy: OnFailure
      volumes:
      - name: sql-volume
        emptyDir: {}  # Temporary storage for SQL file
      - name: csv-volume
        emptyDir: {}  # Temporary storage for CSV files
