// lexitrail#183 — the six crawlable HSK word-list pages.
//
// WHY. "HSK N vocabulary list" is this product's highest-intent query family and its SERP is held
// entirely by small content sites; no high-authority domain locks it. LexiTrail is absent because
// it has **no crawlable page containing a single Chinese word** — every route serves the same
// ~2,871-byte shell.
//
// 🔴 THE URLS END IN `.html`, AND THAT IS NOT A STYLE CHOICE. Measured against a real `serve`
// (this issue's premise said otherwise and was wrong):
//
//     /hsk2.html        REAL FILE ✅   an EXACT filesystem match
//     /hsk3/index.html  REAL FILE ✅   also exact
//     /hsk2             SPA SHELL ✗    needs cleanUrls resolution
//     /hsk3/            SPA SHELL ✗    needs directory-index resolution
//
// `serve-handler` serves an exact file BEFORE applying rewrites; anything needing *resolution* is
// caught first by `serve.json`'s `{"source": "**", "destination": "/index.html"}`. Adding a
// per-path rewrite does not help — measured before AND after the catch-all, order is irrelevant.
// So `cleanUrls: false` is also required, or `/hsk2.html` 301s to `/hsk2` and the catch-all eats it.
//
// PURE ON PURPOSE. Nothing here touches the filesystem, so every claim below is unit-testable and
// the generator script is a thin shell around it. The committed HTML is checked against these
// functions by a drift test — a generated artifact nobody re-generates is a stale artifact.

export const HSK_LEVELS = [1, 2, 3, 4, 5, 6];

export const ORIGIN = 'https://lexitrail.com';

/** `wordset_id` in words.csv is 1..6 for HSK1..6; 7 is the internal `test` set. */
export const isHskWordset = (id) => HSK_LEVELS.includes(Number(id));

const esc = (s) => String(s ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

/** Rows -> {1: [...], ... 6: [...]}, each sorted by word_id so output is DETERMINISTIC.
 *
 * Determinism is load-bearing: the drift test compares generated bytes against committed bytes,
 * and a map-iteration-order render would fail it intermittently, which is worse than not having
 * the test — an intermittent guard gets deleted.
 */
export const groupByLevel = (rows) => {
  const out = Object.fromEntries(HSK_LEVELS.map((n) => [n, []]));
  for (const r of rows) {
    const lvl = Number(r.wordset_id);
    if (!isHskWordset(lvl)) continue;
    if (!r.word) continue;
    out[lvl].push({ id: Number(r.word_id), word: r.word, pinyin: r.def1 || '', english: r.def2 || '' });
  }
  for (const n of HSK_LEVELS) out[n].sort((a, b) => a.id - b.id);
  return out;
};

export const pageFilename = (level) => `hsk${level}.html`;
export const pageUrl = (level, origin = ORIGIN) => `${origin}/hsk${level}.html`;

/** The full page. Self-canonical, unique title, the whole table, ItemList JSON-LD, one CTA.
 *
 * ⚠️ NO links to per-word pages, though this issue's proposal lists them: those are #184 and do
 * not exist. Linking them now would hand Googlebot ~5,600 soft-404s from the six pages meant to
 * establish the site's crawlability — the opposite of the goal. Add them WITH #184.
 */
export const renderPage = (level, words, origin = ORIGIN) => {
  const url = pageUrl(level, origin);
  const title = `HSK ${level} Vocabulary List — all ${words.length} words with pinyin and English`;
  const desc = `The complete HSK ${level} word list: all ${words.length} words with pinyin and `
    + `English meanings, free and in one page. Practise them with spaced repetition on LexiTrail.`;
  const rows = words.map((w, i) => `<tr><td>${i + 1}</td><td lang="zh-Hans">${esc(w.word)}</td>`
    + `<td>${esc(w.pinyin)}</td><td>${esc(w.english)}</td></tr>`).join('\n');
  // 🔴 `JSON.stringify` does NOT escape `<`, so a `</script>` in the source data would CLOSE this
  // block and everything after it becomes markup. My own escape test caught this before merge:
  // the table cells were escaped and the JSON-LD was not, which is the classic split -- one
  // sink hardened, its sibling forgotten. `\u003c` is valid JSON *and* inert in HTML.
  const jsonSafe = (o) => JSON.stringify(o)
    .replace(/</g, '\\u003c').replace(/>/g, '\\u003e').replace(/&/g, '\\u0026');
  const jsonLd = jsonSafe({
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: `HSK ${level} vocabulary list`,
    url,
    numberOfItems: words.length,
    itemListElement: words.map((w, i) => ({
      '@type': 'ListItem', position: i + 1, name: w.word,
      description: `${w.pinyin} — ${w.english}`,
    })),
  });
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<link rel="canonical" href="${url}">
<script type="application/ld+json">${jsonLd}</script>
</head>
<body>
<h1>HSK ${level} vocabulary list</h1>
<p>This page lists every word in the HSK ${level} vocabulary — ${words.length} entries, each with
its simplified hanzi, pinyin and English meaning. HSK ${level} is one of the six levels of the
Hanyu Shuiping Kaoshi, China's standardised Chinese proficiency test. Reading a list is not the
same as knowing it: the words that stick are the ones you are asked to recall just as you are about
to forget them. LexiTrail drills this list with spaced repetition, free and without an account, so
you can start on the words below straight away.</p>
<p><a href="${origin}/game/${level}/PRACTICE">Practise the HSK ${level} list now &rarr;</a></p>
<table>
<thead><tr><th>#</th><th>Hanzi</th><th>Pinyin</th><th>English</th></tr></thead>
<tbody>
${rows}
</tbody>
</table>
<p><a href="${origin}/game/${level}/PRACTICE">Start practising HSK ${level} &rarr;</a></p>
<nav><p>Other levels: ${HSK_LEVELS.filter((n) => n !== level)
    .map((n) => `<a href="${origin}/hsk${n}.html">HSK ${n}</a>`).join(' · ')}</p></nav>
</body>
</html>
`;
};

/** `<url>` entries for sitemap.xml. `lastmod` is passed in, never `new Date()` — a generator that
 * stamps "now" produces a diff on every run and trains reviewers to ignore its output. */
export const renderSitemapEntries = (lastmod, origin = ORIGIN) =>
  HSK_LEVELS.map((n) => `  <url>\n    <loc>${pageUrl(n, origin)}</loc>\n`
    + `    <lastmod>${lastmod}</lastmod>\n    <changefreq>monthly</changefreq>\n`
    + `    <priority>0.8</priority>\n  </url>`).join('\n');
