// lexitrail#184 — pure renderer for the ~5,600 per-word pages.
//
// Sibling of hskPages.js and deliberately shaped the same way: every decision lives here and is
// unit-tested; ui/scripts/generate-word-pages.js only does I/O. See hskPages.js for why the output
// is COMMITTED rather than built (the Docker build context is `ui/`, so terraform/csv/words.csv —
// one directory UP — does not exist inside the image; a build-time generator would work locally,
// pass review, and produce nothing in production).
import { HSK_LEVELS, ORIGIN, isHskWordset } from './hskPages';

const esc = (s) => String(s ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

// 🔴 JSON.stringify does NOT escape `<`, so a `</script>` in source data would close the JSON-LD
// block and everything after it becomes markup. Same sink, same fix, as hskPages.js — kept as its
// own copy rather than imported, because hskPages.js does not export it and widening that module's
// API for one helper is a worse trade than eight duplicated lines.
const jsonSafe = (o) => JSON.stringify(o)
  .replace(/</g, '\\u003c').replace(/>/g, '\\u003e').replace(/&/g, '\\u0026');

/** The on-disk name for a word page. NOT url-encoded: this is a FILENAME, and the filesystem
 * takes the raw UTF-8 bytes. Encoding here would create a file literally named `%E6%88%91.html`,
 * which then 404s for the encoded request the browser actually sends. Measured 2026-08-29 against
 * `serve` itself: the raw-named file answers `/hsk3/%E6%88%91.html` with 200 and the page body. */
export const wordFilename = (word) => `${word}.html`;

/** The public URL. Percent-ENCODED, because this string goes into href/canonical/sitemap, where a
 * raw multi-byte character is not valid. `encodeURIComponent` is correct per-segment: it escapes
 * `/` too, which a hanzi never contains but a malformed row might. */
export const wordUrl = (level, word, origin = ORIGIN) =>
  `${origin}/hsk${level}/${encodeURIComponent(word)}.html`;

/** Rows -> [{level, id, word, pinyin, english}], sorted by (level, word_id).
 *
 * Determinism is load-bearing for the same reason as hskPages.groupByLevel: the drift test compares
 * generated bytes to committed bytes, and an intermittent guard gets deleted rather than fixed.
 *
 * 🔴 A hanzi can appear TWICE in one level as two SENSES, and the fix is to MERGE them, not to drop
 * one. words.csv carries HSK2 `对` as word_id 301 (`duì`, "to") and 302 (`duì`, "right") — the same
 * character, two meanings, two rows. They render to the same filename, so a first-wins rule would
 * silently keep "to" and lose "right", i.e. drop a meaning AND keep the weaker gloss, with the page
 * count disagreeing with the row count for a reason invisible in the diff.
 *
 * Merging is also the right SEO shape: one hanzi is one thing a person searches for, so it should
 * be one canonical page carrying every sense, not two pages splitting the link equity or one page
 * quietly missing half the answer.
 *
 * `sensesMerged` counts the extra rows folded in, so the generator can print why 5,000 rows became
 * 4,999 pages rather than leaving a discrepancy nobody can explain later.
 */
export const collectWords = (rows) => {
  const byKey = new Map();
  let sensesMerged = 0;
  for (const r of rows) {
    const level = Number(r.wordset_id);
    if (!isHskWordset(level)) continue;
    if (!r.word) continue;
    const key = `${level}/${r.word}`;
    const pinyin = r.def1 || '';
    const english = r.def2 || '';
    const seen = byKey.get(key);
    if (!seen) {
      byKey.set(key, {
        level, id: Number(r.word_id), word: r.word,
        pinyin, english,
        // Kept separate from `english` so the renderer can list senses without re-splitting a
        // joined string -- a join followed by a split is a lossy round trip the moment a gloss
        // legitimately contains the separator.
        senses: [{ pinyin, english }],
      });
      continue;
    }
    sensesMerged += 1;
    seen.senses.push({ pinyin, english });
    // The headline gloss stays the FIRST by word_id; additional senses are additive. Readings are
    // de-duplicated because the common case (`对` -> duì, duì) is one pronunciation, two meanings,
    // and repeating it reads as an error.
    const readings = [...new Set(seen.senses.map((x) => x.pinyin).filter(Boolean))];
    seen.pinyin = readings.join(', ');
    seen.english = seen.senses.map((x) => x.english).filter(Boolean).join('; ');
  }
  const out = [...byKey.values()].sort((a, b) => (a.level - b.level) || (a.id - b.id));
  return { words: out, sensesMerged };
};

/** One word page. `prev`/`next` are the adjacent words IN THE SAME LEVEL, or null at the ends.
 *
 * 🔴 The prev/next links are not decoration — they are the CRAWL PATH. Until sitemap.xml carries
 * these ~5,600 URLs, a chain of prev/next from the six level pages is the only way Googlebot can
 * reach a word page at all. They also mean the pages are discoverable in the order a human would
 * read them, which is what makes this a list rather than 5,600 orphans.
 */
export const renderWordPage = (w, { prev = null, next = null } = {}, origin = ORIGIN) => {
  const url = wordUrl(w.level, w.word, origin);
  const senses = w.senses || [{ pinyin: w.pinyin, english: w.english }];
  const levelUrl = `${origin}/hsk${w.level}.html`;
  const gloss = [w.pinyin, w.english].filter(Boolean).join(' — ');
  const title = `${w.word}${gloss ? ` (${gloss})` : ''} — HSK ${w.level} Chinese word`;
  const desc = `${w.word}${w.pinyin ? `, pinyin ${w.pinyin}` : ''}${w.english ? `, means "${w.english}"` : ''}. `
    + `An HSK ${w.level} word. Practise it with spaced repetition on LexiTrail, free.`;
  const jsonLd = jsonSafe({
    '@context': 'https://schema.org',
    '@type': 'DefinedTerm',
    name: w.word,
    url,
    description: gloss,
    inDefinedTermSet: { '@type': 'DefinedTermSet', name: `HSK ${w.level}`, url: levelUrl },
  });
  const nav = [
    prev ? `<a rel="prev" href="${wordUrl(prev.level, prev.word, origin)}">&larr; ${esc(prev.word)}</a>` : '',
    `<a href="${levelUrl}">All HSK ${w.level} words</a>`,
    next ? `<a rel="next" href="${wordUrl(next.level, next.word, origin)}">${esc(next.word)} &rarr;</a>` : '',
  ].filter(Boolean).join(' &middot; ');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<link rel="canonical" href="${url}">
${prev ? `<link rel="prev" href="${wordUrl(prev.level, prev.word, origin)}">\n` : ''}${next ? `<link rel="next" href="${wordUrl(next.level, next.word, origin)}">\n` : ''}<meta property="og:type" content="article">
<meta property="og:url" content="${url}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:image" content="${origin}/images/og/generated/og-landscape.png">
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="${url}">
<meta property="twitter:title" content="${esc(title)}">
<meta property="twitter:description" content="${esc(desc)}">
<script type="application/ld+json">${jsonLd}</script>
</head>
<body>
<h1 lang="zh-Hans">${esc(w.word)}</h1>
<dl>
<dt>Pinyin</dt><dd>${esc(w.pinyin)}</dd>
<dt>English</dt><dd>${esc(w.english)}</dd>
<dt>HSK level</dt><dd><a href="${levelUrl}">HSK ${w.level}</a></dd>
</dl>${senses.length > 1 ? `
<h2>Senses</h2>
<ol>
${senses.map((s) => `<li>${esc([s.pinyin, s.english].filter(Boolean).join(' — '))}</li>`).join('\n')}
</ol>` : ''}
<p><span lang="zh-Hans">${esc(w.word)}</span>${w.pinyin ? ` is pronounced <em>${esc(w.pinyin)}</em>` : ''}${w.english ? ` and means ${senses.length > 1 ? `&ldquo;${esc(senses[0].english)}&rdquo; (and ${senses.length - 1} further sense${senses.length > 2 ? 's' : ''} below)` : `&ldquo;${esc(w.english)}&rdquo;`}` : ''}. It is one of the words in the HSK ${w.level} vocabulary, a level of the Hanyu Shuiping Kaoshi, China&rsquo;s standardised Chinese proficiency test. Recognising a word on a page and recalling it when you need it are different skills, and only the second survives a conversation &mdash; which is why LexiTrail shows you <span lang="zh-Hans">${esc(w.word)}</span> again just before you would have forgotten it, rather than on a fixed schedule.</p>
<p><a href="${origin}/game/${w.level}/PRACTICE">Practise HSK ${w.level} with ${esc(w.word)} &rarr;</a></p>
<nav>${nav}</nav>
</body>
</html>
`;
};

/** `<url>` entries for sitemap.xml. `lastmod` is passed in, never `new Date()` — a generator that
 * stamps today's date rewrites every entry on every run and makes the drift test unusable. */
export const renderWordSitemapEntries = (words, lastmod, origin = ORIGIN) =>
  words.map((w) => `  <url>\n    <loc>${wordUrl(w.level, w.word, origin)}</loc>\n`
    + `    <lastmod>${lastmod}</lastmod>\n    <changefreq>monthly</changefreq>\n`
    + `    <priority>0.5</priority>\n  </url>`).join('\n');

export { HSK_LEVELS };
